"""modify_requirement_rule

Revision ID: 0178b8db12b3
Revises: ad4e2c93657d
Create Date: 2026-05-19 09:57:44.581409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0178b8db12b3'
down_revision: Union[str, Sequence[str], None] = 'ad4e2c93657d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requirement_rule', 'required_course_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requirement_rule', 'required_course_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
