"""add_requirment_rule_hint

Revision ID: 2133e8a7986c
Revises: 0178b8db12b3
Create Date: 2026-05-20 04:58:36.310054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2133e8a7986c'
down_revision: Union[str, Sequence[str], None] = '0178b8db12b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement_rule', sa.Column('hint', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement_rule', 'hint')
    # ### end Alembic commands ###
