"""modify_course_record

Revision ID: 6c8493c00773
Revises: b44929f8478f
Create Date: 2026-05-21 16:23:25.483111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c8493c00773'
down_revision: Union[str, Sequence[str], None] = 'b44929f8478f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_record', 'grade',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_record', 'grade',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
