"""modify_gradutaion_requirements

Revision ID: 9a08999b5c81
Revises: 6c8493c00773
Create Date: 2026-05-22 09:48:12.452973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a08999b5c81'
down_revision: Union[str, Sequence[str], None] = '6c8493c00773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graduation_requirements', 'total_credits_threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graduation_requirements', sa.Column('total_credits_threshold', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
