"""init_all_tables

Revision ID: ad4e2c93657d
Revises: 
Create Date: 2026-05-17 16:38:09.522920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad4e2c93657d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_id', sa.String(length=3), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('department_id', name=op.f('pk_department'))
    )
    op.create_table('course_information',
    sa.Column('course_id', sa.String(length=9), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_type', sa.String(length=5), nullable=False),
    sa.Column('teacher_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.String(length=3), nullable=False),
    sa.Column('credits', mysql.INTEGER(display_width=3), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], name=op.f('fk_course_information_department_id_department')),
    sa.PrimaryKeyConstraint('course_id', name=op.f('pk_course_information'))
    )
    op.create_table('graduation_requirements',
    sa.Column('department_id', sa.String(length=3), nullable=False),
    sa.Column('required_course_credits', sa.Integer(), nullable=False),
    sa.Column('total_credits_threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], name=op.f('fk_graduation_requirements_department_id_department')),
    sa.PrimaryKeyConstraint('department_id', name=op.f('pk_graduation_requirements'))
    )
    op.create_table('requirement_rule',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.String(length=3), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=True),
    sa.Column('required_course_count', sa.Integer(), nullable=False),
    sa.Column('parent_rule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], name=op.f('fk_requirement_rule_department_id_department')),
    sa.ForeignKeyConstraint(['parent_rule_id'], ['requirement_rule.rule_id'], name=op.f('fk_requirement_rule_parent_rule_id_requirement_rule')),
    sa.PrimaryKeyConstraint('rule_id', 'department_id', name=op.f('pk_requirement_rule'))
    )
    op.create_table('student_account',
    sa.Column('student_id', sa.String(length=9), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('department_major1', sa.String(length=3), nullable=False),
    sa.Column('department_major2', sa.String(length=3), nullable=True),
    sa.Column('department_auxiliary', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['department_auxiliary'], ['department.department_id'], name=op.f('fk_student_account_department_auxiliary_department')),
    sa.ForeignKeyConstraint(['department_major1'], ['department.department_id'], name=op.f('fk_student_account_department_major1_department')),
    sa.ForeignKeyConstraint(['department_major2'], ['department.department_id'], name=op.f('fk_student_account_department_major2_department')),
    sa.PrimaryKeyConstraint('student_id', name=op.f('pk_student_account'))
    )
    op.create_table('teacher_account',
    sa.Column('teacher_id', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], name=op.f('fk_teacher_account_department_id_department')),
    sa.PrimaryKeyConstraint('teacher_id', name=op.f('pk_teacher_account'))
    )
    op.create_table('course_record',
    sa.Column('student_id', sa.String(length=9), nullable=False),
    sa.Column('course_id', sa.String(length=9), nullable=False),
    sa.Column('semester', sa.String(length=5), nullable=False),
    sa.Column('grade', mysql.INTEGER(display_width=3), nullable=False),
    sa.Column('passed_state', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_information.course_id'], name=op.f('fk_course_record_course_id_course_information')),
    sa.ForeignKeyConstraint(['student_id'], ['student_account.student_id'], name=op.f('fk_course_record_student_id_student_account')),
    sa.PrimaryKeyConstraint('student_id', 'course_id', 'semester', name=op.f('pk_course_record'))
    )
    op.create_table('requirement_course_mapping',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=9), nullable=False),
    sa.Column('alternative_course_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_information.course_id'], name=op.f('fk_requirement_course_mapping_course_id_course_information')),
    sa.ForeignKeyConstraint(['rule_id'], ['requirement_rule.rule_id'], name=op.f('fk_requirement_course_mapping_rule_id_requirement_rule')),
    sa.PrimaryKeyConstraint('rule_id', 'course_id', name=op.f('pk_requirement_course_mapping'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_course_mapping')
    op.drop_table('course_record')
    op.drop_table('teacher_account')
    op.drop_table('student_account')
    op.drop_table('requirement_rule')
    op.drop_table('graduation_requirements')
    op.drop_table('course_information')
    op.drop_table('department')
    # ### end Alembic commands ###
