"""modify_course_record

Revision ID: b44929f8478f
Revises: 2133e8a7986c
Create Date: 2026-05-21 08:46:14.257111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b44929f8478f'
down_revision: Union[str, Sequence[str], None] = '2133e8a7986c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_record', sa.Column('status', sa.String(length=10), nullable=False))
    op.alter_column('course_record', 'grade',
               existing_type=mysql.INTEGER(),
               type_=mysql.FLOAT(precision=2),
               existing_nullable=False)
    op.drop_column('course_record', 'passed_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_record', sa.Column('passed_state', mysql.VARCHAR(length=1), nullable=False))
    op.alter_column('course_record', 'grade',
               existing_type=mysql.FLOAT(precision=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('course_record', 'status')
    # ### end Alembic commands ###
